# Champion - Very aggressive, expert tactics

base_act_chance = 2
base_fwd_jump_chance = 3
base_back_jump_chance = 5
base_still_jump_chance = 25
random_attack_chance = 4
base_act_timer = 20
block_chance = 2
aggressive_tactics = 1
jump_frequency_mult = 180
