# Deadly - Expert tactics, constant pressure

base_act_chance = 1
base_fwd_jump_chance = 2
base_back_jump_chance = 3
base_still_jump_chance = 15
random_attack_chance = 2
base_act_timer = 18
block_chance = 1
aggressive_tactics = 1
jump_frequency_mult = 200
