# Rookie - Below average, somewhat defensive

base_act_chance = 15
base_fwd_jump_chance = 40
base_back_jump_chance = 45
base_still_jump_chance = 70
random_attack_chance = 35
base_act_timer = 32
block_chance = 40
aggressive_tactics = 0
jump_frequency_mult = 60
