# Ultimate - Maximum aggression, relentless pressure

base_act_chance = 1
base_fwd_jump_chance = 1
base_back_jump_chance = 2
base_still_jump_chance = 10
random_attack_chance = 1
base_act_timer = 16
block_chance = 1
aggressive_tactics = 1
jump_frequency_mult = 220
