# World Class - Aggressive, high skill

base_act_chance = 4
base_fwd_jump_chance = 8
base_back_jump_chance = 12
base_still_jump_chance = 35
random_attack_chance = 8
base_act_timer = 24
block_chance = 5
aggressive_tactics = 1
jump_frequency_mult = 150
